### ISSUE TITLE
Compiling fails for 'ss1 ss2 ss3' (ss = simple selector, space = combinator)

### ISSUE THREAD

**Issue by slukits** [ericchiang/css#7]
Thank you for this package! I'd like to use it but it fails for

`_, err := css.Compile("body p em")`
`fmt.Println(err)`

with the error message

`expected [EOF ,], got IDENT "em"`

The selector seems valid to me according to https://www.w3.org/TR/selectors-3?

It doesn't fail if the second combinator is any other than space.

*Note* having a look at 'lex.go' whitespace is not in combinator char while comma is which is according to selectors-3 spec not an combinator.  But since I have never worked with a lexer I dont realy know how to fix that.

**Comment by ericchiang** [comment]
This is now fixed
